#!/bin/bash -l
#SBATCH --constraint=gpu
#SBATCH --cpus-per-task=1
#SBATCH --qos=debug
#SBATCH --nodes=1
#SBATCH --time=00:04:00
#SBATCH --cpu-freq=1400000
#SBATCH --job-name=job-offload
#SBATCH --output=job-offload.o%j
#SBATCH --error=job-offload.e%j

export LIBOMPTARGETINFO=4

echo ""
srun -n 1 nvprof ./sobel_cpu_omp_offload

# eof

