#!/bin/bash -l
#SBATCH -N 1
#SBATCH -c 10
#SBATCH -G 1
#SBATCH -C gpu
#SBATCH -t 5:00
#SBATCH -J queue
#SBATCH --job-name=job-offload
#SBATCH --output=job-offload.o%j
#SBATCH --error=job-offload.e%j

export LIBOMPTARGETINFO=4

echo ""
srun -n 1 nvprof ./sobel_cpu_omp_offload

# eof

